import { getValidInstagramAccessToken } from "@/lib/instagram/token-manager";

const INSTAGRAM_API_VERSION = "v26.0";

type InstagramMessengerProfileResponse = {
  result?: string;
  error?: {
    message?: string;
    type?: string;
    code?: number;
    error_subcode?: number;
    fbtrace_id?: string;
  };
};

type IceBreakerPayload = {
  question: string;
  payload: string;
};

type PersistentMenuItemPayload = {
  title: string;
  payload: string;
};

function getMessengerProfileUrl(instagramUserId: string) {
  return `https://graph.instagram.com/${INSTAGRAM_API_VERSION}/${instagramUserId}/messenger_profile`;
}

async function callMessengerProfileApi({
  instagramAccountId,
  instagramUserId,
  method,
  body,
  fields,
}: {
  instagramAccountId: string;
  instagramUserId: string;
  method: "GET" | "POST" | "DELETE";
  body?: Record<string, unknown>;
  fields?: string;
}) {
  const accessToken = await getValidInstagramAccessToken(instagramAccountId);

  const url = new URL(getMessengerProfileUrl(instagramUserId));

  url.searchParams.set("platform", "instagram");

  if (fields) {
    url.searchParams.set("fields", fields);
  }

  console.log("[Instagram Messenger Profile] Request:", {
    method,
    url: url.toString(),
    body: body ?? null,
  });

  const response = await fetch(url.toString(), {
    method,
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    ...(body
      ? {
          body: JSON.stringify(body),
        }
      : {}),
    cache: "no-store",
  });

  const responseText = await response.text();

  let data: InstagramMessengerProfileResponse | unknown;

  try {
    data = JSON.parse(responseText);
  } catch {
    data = responseText;
  }

  console.log("[Instagram Messenger Profile] Response:", {
    status: response.status,
    ok: response.ok,
    data,
  });

  if (!response.ok) {
    const errorData = data as InstagramMessengerProfileResponse;

    const message =
      errorData?.error?.message ||
      `Instagram API returned HTTP ${response.status}`;

    throw new Error(message);
  }

  return data;
}

/**
 * Configure Instagram Ice Breakers.
 *
 * The payload generated by SmartDirect is stored in Prisma
 * and sent to Meta unchanged.
 *
 * This is important because the webhook later receives
 * the same payload and uses it to find the corresponding
 * IceBreaker and Automation.
 */
export async function setInstagramIceBreakers({
  instagramAccountId,
  instagramUserId,
  iceBreakers,
}: {
  instagramAccountId: string;
  instagramUserId: string;
  iceBreakers: IceBreakerPayload[];
}) {
  if (iceBreakers.length > 4) {
    throw new Error("Instagram allows a maximum of 4 Ice Breakers");
  }

  const normalizedItems = iceBreakers.map((item) => {
    const question = item.question.trim();
    const payload = item.payload.trim();

    if (!question) {
      throw new Error("Ice Breaker question cannot be empty");
    }

    if (!payload) {
      throw new Error("Ice Breaker payload cannot be empty");
    }

    if (question.length > 80) {
      throw new Error("Ice Breaker question must be 80 characters or less");
    }

    return {
      question,
      payload,
    };
  });

  if (normalizedItems.length === 0) {
    return deleteInstagramIceBreakers({
      instagramAccountId,
      instagramUserId,
    });
  }

  return callMessengerProfileApi({
    instagramAccountId,
    instagramUserId,
    method: "POST",
    body: {
      platform: "instagram",
      ice_breakers: [
        {
          locale: "default",
          call_to_actions: normalizedItems,
        },
      ],
    },
  });
}

/**
 * Remove all Instagram Ice Breakers.
 */
export async function deleteInstagramIceBreakers({
  instagramAccountId,
  instagramUserId,
}: {
  instagramAccountId: string;
  instagramUserId: string;
}) {
  return callMessengerProfileApi({
    instagramAccountId,
    instagramUserId,
    method: "DELETE",
    fields: "ice_breakers",
  });
}

/**
 * Configure Instagram Persistent Menu.
 *
 * SmartDirect currently allows up to 3 top-level items.
 */
export async function setInstagramPersistentMenu({
  instagramAccountId,
  instagramUserId,
  items,
}: {
  instagramAccountId: string;
  instagramUserId: string;
  items: PersistentMenuItemPayload[];
}) {
  if (items.length > 3) {
    throw new Error(
      "Instagram Persistent Menu supports up to 3 top-level items",
    );
  }

  const normalizedItems = items.map((item) => {
    const title = item.title.trim();
    const payload = item.payload.trim();

    if (!title) {
      throw new Error("Persistent menu item title cannot be empty");
    }

    if (!payload) {
      throw new Error("Persistent menu item payload cannot be empty");
    }

    if (title.length > 30) {
      throw new Error(
        "Persistent menu item title must be 30 characters or less",
      );
    }

    return {
      type: "postback",
      title,
      payload,
    };
  });

  if (normalizedItems.length === 0) {
    return deleteInstagramPersistentMenu({
      instagramAccountId,
      instagramUserId,
    });
  }

  return callMessengerProfileApi({
    instagramAccountId,
    instagramUserId,
    method: "POST",
    body: {
      platform: "instagram",
      persistent_menu: [
        {
          locale: "default",
          composer_input_disabled: false,
          call_to_actions: normalizedItems,
        },
      ],
    },
  });
}

/**
 * Remove Persistent Menu from Instagram.
 */
export async function deleteInstagramPersistentMenu({
  instagramAccountId,
  instagramUserId,
}: {
  instagramAccountId: string;
  instagramUserId: string;
}) {
  return callMessengerProfileApi({
    instagramAccountId,
    instagramUserId,
    method: "DELETE",
    fields: "persistent_menu",
  });
}

/**
 * Backward-compatible aliases.
 *
 * If any older part of the project still uses these names,
 * it will continue to work without changing that code.
 */
export const configureInstagramIceBreakers = setInstagramIceBreakers;

export async function configureInstagramPersistentMenu({
  instagramAccountId,
  instagramUserId,
  enabled,
  items,
}: {
  instagramAccountId: string;
  instagramUserId: string;
  enabled: boolean;
  items: Array<{
    title: string;
    payload: string;
  }>;
}) {
  if (!enabled || items.length === 0) {
    return deleteInstagramPersistentMenu({
      instagramAccountId,
      instagramUserId,
    });
  }

  return setInstagramPersistentMenu({
    instagramAccountId,
    instagramUserId,
    items,
  });
}
