"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Alert, Avatar, Button, Card, Divider, Input, InputNumber, Skeleton, Table, Tag, Typography, message } from "antd";
import { ArrowRight, Check, Minus, Pause, Plus, RefreshCw } from "lucide-react";

type UserDetail={id:string;name:string;email:string;role:string;createdAt:string;instagramAccounts:{id:string;igUsername:string;igUserId:string;isConnected:boolean;createdAt:string}[];subscriptions:{id:string;planKey:string;status:string;source:string;startedAt:string;expiresAt:string;note?:string|null;autoRenew:boolean;createdAt:string}[]};

export default function UserDetailPage(){
 const params=useParams<{id:string}>(); const router=useRouter(); const [user,setUser]=useState<UserDetail|null>(null); const [loading,setLoading]=useState(true); const [days,setDays]=useState(30); const [planKey,setPlanKey]=useState("monthly"); const [busy,setBusy]=useState(false); const [msgApi,msgHolder]=message.useMessage();
 const load=async()=>{setLoading(true);try{const r=await fetch(`/api/admin/users/${params.id}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message);setUser(j);const s=j.subscriptions?.[0];if(s)setPlanKey(s.planKey);}catch(e){msgApi.error(e instanceof Error?e.message:"خطا");}finally{setLoading(false);}};
 useEffect(()=>{if(params.id)load();},[params.id]);
 const action=async(actionName:string,customDays?:number)=>{setBusy(true);try{const r=await fetch(`/api/admin/users/${params.id}/subscription`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:actionName,days:customDays??days,planKey})});const j=await r.json();if(!r.ok)throw new Error(j.message);msgApi.success("اشتراک به‌روزرسانی شد");await load();}catch(e){msgApi.error(e instanceof Error?e.message:"خطا");}finally{setBusy(false);}};
 if(loading)return <div className="space-y-4"><Skeleton active/><Skeleton active/></div>;
 if(!user)return <Alert type="error" message="کاربر پیدا نشد"/>;
 const current=user.subscriptions[0]; const active=current?.status==="ACTIVE"&&new Date(current.expiresAt)>new Date();
 const statusLabel=active?"فعال":current?.status==="SUSPENDED"?"معلق":current?"منقضی":"بدون اشتراک";
 return <>{msgHolder}<div className="space-y-5">
  <div className="flex items-center gap-2"><Button type="text" icon={<ArrowRight size={18}/>} onClick={()=>router.push("/rickandmorty/users")}>بازگشت</Button><div className="mr-2"><Typography.Title level={3} className="!mb-1 !text-[22px]">{user.name}</Typography.Title><Typography.Text className="!text-[#64748B]">{user.email}</Typography.Text></div></div>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
   <Card title="اطلاعات کاربر" className="!border-[#E2E8F0] !shadow-none"><div className="flex items-center gap-3"><Avatar size={48} className="!bg-[#EFF6FF] !text-[#2563EB]">{user.name[0]}</Avatar><div><div className="font-semibold">{user.name}</div><div className="text-xs text-[#64748B]">{user.email}</div></div></div><Divider/><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-[#64748B]">نقش</span><Tag color={user.role==="ADMIN"?"blue":"default"}>{user.role==="ADMIN"?"مدیر":"کاربر"}</Tag></div><div className="flex justify-between"><span className="text-[#64748B]">عضویت</span><span>{new Date(user.createdAt).toLocaleDateString("fa-IR")}</span></div><div className="flex justify-between"><span className="text-[#64748B]">پیج متصل</span><span>{user.instagramAccounts.length}</span></div></div></Card>
   <Card title="پیج‌های متصل" className="!border-[#E2E8F0] !shadow-none lg:col-span-2">{user.instagramAccounts.length?<div className="grid gap-3 sm:grid-cols-2">{user.instagramAccounts.map(a=><div key={a.id} className="rounded-xl border border-[#E2E8F0] p-4"><div className="flex items-center justify-between gap-2"><span className="font-medium">@{a.igUsername}</span><Tag color={a.isConnected?"green":"default"}>{a.isConnected?"متصل":"قطع"}</Tag></div><div className="mt-2 truncate text-xs text-[#64748B]">{a.igUserId}</div></div>)}</div>:<div className="py-8 text-center text-sm text-[#64748B]">پیجی متصل نشده است</div>}</Card>
  </div>
  <Card title="مدیریت اشتراک" className="!border-[#E2E8F0] !shadow-none">
   {current?<div className="mb-5 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-semibold">{current.planKey}</div><div className="mt-1 text-xs text-[#64748B]">انقضا: {new Date(current.expiresAt).toLocaleString("fa-IR")}</div></div><Tag color={active?"green":current.status==="SUSPENDED"?"orange":"red"}>{statusLabel}</Tag></div></div>:<Alert className="mb-5" type="warning" message="این کاربر اشتراک ندارد"/>}
   <div className="grid gap-3 md:grid-cols-2"><div><Typography.Text type="secondary">پلن</Typography.Text><Input value={planKey} onChange={e=>setPlanKey(e.target.value)} className="mt-1"/></div><div><Typography.Text type="secondary">تعداد روز</Typography.Text><InputNumber min={1} value={days} onChange={v=>setDays(Number(v)||1)} className="mt-1 !w-full"/></div></div>
   <div className="mt-4 flex flex-wrap gap-2"><Button type="primary" loading={busy} icon={<Check size={16}/>} onClick={()=>action(current?"activate":"create",days)}>{current?"فعال‌سازی":"ایجاد اشتراک"}</Button><Button loading={busy} icon={<Plus size={16}/>} onClick={()=>action("extend",7)}>+۷ روز</Button><Button loading={busy} icon={<Plus size={16}/>} onClick={()=>action("extend",30)}>+۳۰ روز</Button><Button loading={busy} icon={<Plus size={16}/>} onClick={()=>action("extend",90)}>+۹۰ روز</Button><Button danger loading={busy} icon={<Minus size={16}/>} onClick={()=>action("adjust",-7)}>−۷ روز</Button>{current&&<Button loading={busy} icon={<Pause size={16}/>} onClick={()=>action("suspend")}>تعلیق</Button>}<Button icon={<RefreshCw size={16}/>} onClick={load}>به‌روزرسانی</Button></div>
  </Card>
  <Card title="تاریخچه اشتراک" className="!border-[#E2E8F0] !shadow-none"><Table rowKey="id" dataSource={user.subscriptions} pagination={false} scroll={{x:700}} columns={[{title:"پلن",dataIndex:"planKey"},{title:"وضعیت",dataIndex:"status",render:v=><Tag color={v==="ACTIVE"?"green":v==="SUSPENDED"?"orange":"red"}>{v}</Tag>},{title:"منبع",dataIndex:"source"},{title:"شروع",dataIndex:"startedAt",render:v=>new Date(v).toLocaleDateString("fa-IR")},{title:"انقضا",dataIndex:"expiresAt",render:v=>new Date(v).toLocaleDateString("fa-IR")},{title:"یادداشت",dataIndex:"note"}]}/></Card>
 </div></>;
}
